services:
  postgres:
    restart: always
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./resources/tables-test.sql:/docker-entrypoint-initdb.d/init.sql
